# Generated by Django 5.2.7 on 2025-10-05 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0002_alter_category_options_alter_order_options_and_more'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'دفعة', 'verbose_name_plural': 'المدفوعات'},
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'verbose_name': 'تقرير', 'verbose_name_plural': 'التقارير'},
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='commerce.order', verbose_name='الطلب'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(default='غير مدفوع', max_length=50, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم العملية'),
        ),
        migrations.AlterField(
            model_name='report',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التقرير'),
        ),
        migrations.AlterField(
            model_name='report',
            name='details',
            field=models.TextField(blank=True, null=True, verbose_name='التفاصيل'),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(max_length=100, verbose_name='نوع التقرير'),
        ),
    ]
